## 0. Imports

In [1]:
import numpy as np

## 1. Constants

In [132]:
def printa(valor1, valor2):
  return valor1, valor2

In [71]:
def shape(valor):
  return 'shape: ', valor.shape

# Numpy

## 1. Criação de Arrays

In [ ]:
help(np.array)  # o help serve para ver o que esse método aceita

### 1.1 Criação de array 1D

In [77]:
lista = [1, 2, 3]
a = np.array(lista)
# x = np.array([1, 2, 3])

In [133]:
printa('a', a)

('a', array([1, 2, 3]))

In [80]:
shape(a)

('shape: ', (3,))

In [84]:
type(a)

numpy.ndarray

### 1.2 Criação de array 2D: listas aninhadas

In [81]:
lista = [[1, 2], [3, 4]]
b = np.array(lista)

In [134]:
printa('b', b)

('b', array([[1, 2],
        [3, 4]]))

In [83]:
shape(b)

('shape: ', (2, 2))

In [85]:
type(b)

numpy.ndarray

### 1.3 Array contendo apenas 0's

In [86]:
dim = (3, 2)
c = np.zeros(dim)

In [135]:
printa('c', c)

('c', array([[0., 0.],
        [0., 0.],
        [0., 0.]]))

In [88]:
shape(c)

('shape: ', (3, 2))

### 1.4 Array contendo apenas 1's

In [89]:
size = (2, 2)
d = np.ones(size)

In [136]:
printa('d', d)

('d', array([[1., 1.],
        [1., 1.]]))

In [91]:
shape(d)

('shape: ', (2, 2))

### 1.5 Criação de valores dentro de um intervalo

In [ ]:
help(np.linspace)

In [92]:
x_min, x_max = 5, 15
e = np.linspace(start=x_min, stop=x_max, num=6)

In [137]:
printa('e', e)

('e', array([ 5.,  7.,  9., 11., 13., 15.]))

In [94]:
shape(e)

('shape: ', (6,))

#### 1.6 Criação da matriz identidade

In [42]:
n = 4 # recebe o mesmo numero de linhas e colunas
x = np.eye(n)

In [43]:
print('x:\n', x)

x:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [44]:
print('shape:', x.shape)

shape: (4, 4)


### 1.6 Criação de valores aleatórios

In [95]:
f = np.random.random(size=(2, 3))

In [138]:
printa('f', f)

('f', array([[0.77132064, 0.02075195, 0.63364823],
        [0.74880388, 0.49850701, 0.22479665]]))

In [97]:
shape(f)

('shape: ', (2, 3))

## 2. Indexação de arrays

In [98]:
g = np.linspace(10, 100, num=10)

In [139]:
printa('g', g)

('g', array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]))

### 2.1 Arrays 1D

#### 2.1.1 Extração de elementos

In [103]:
print('1:', g[0])
print('2:', g[1])
print('10:', g[9])
print('10:', g[-1])

1: 10.0
2: 20.0
10: 100.0
10: 100.0


#### 2.1.2 Slicing: extração de subarrays

In [108]:
print('1 e 2:', g[0:2])
print('1 e 2:', g[:2])
print('9 e 10:', g[-2:])
print('9 e 10:', g[8:])

1 e 2: [10. 20.]
1 e 2: [10. 20.]
9 e 10: [ 90. 100.]
9 e 10: [ 90. 100.]


### 2.2 Reshape de arrays 2D (matrizes)

In [109]:
h = g.reshape(2, 5) # reshape de g para 2 linhas e 5 colunas

In [140]:
printa('h', h)

('h', array([[ 10.,  20.,  30.,  40.,  50.],
        [ 60.,  70.,  80.,  90., 100.]]))

In [112]:
i = g.reshape(5, 2) # reshape de g para 5 linhas e 2 colunas

In [141]:
printa('i', i)

('i', array([[ 10.,  20.],
        [ 30.,  40.],
        [ 50.,  60.],
        [ 70.,  80.],
        [ 90., 100.]]))

#### 2.2.1 Extração de elementos

In [122]:
print('primeira linha, segunda coluna', h[0, 1])
print('segunda linha, penultima coluna', h[1, -2])
print('ultima linha, ultima coluna', h[-1, -1])
print('ultima linha, ultima coluna', h[1, 4])

primeira linha, segunda coluna 20.0
segunda linha, penultima coluna 90.0
ultima linha, ultima coluna 100.0
ultima linha, ultima coluna 100.0


#### 2.2.2 Slicing: estração de subarrays

In [130]:
print('primeira linha inteira', h[0, :])
print('primeira linha, segunda a quarta coluna', h[0, 1:4])
print('ultima coluna inteira\n', h[:, [-1]]) # ao inserir o indice da coluna, ele retona na dimensao correta
print('ultima coluna inteira fora da dimensao', h[:, -1]) # fora da dimensao, veio como linha, sendo que é coluna

primeira linha inteira [10. 20. 30. 40. 50.]
primeira linha, segunda a quarta coluna [20. 30. 40.]
ultima coluna inteira
 [[ 50.]
 [100.]]
ultima coluna inteira fora da dimensao [ 50. 100.]


### 2.3 Compartilhamento de memória em subarrays

In [146]:
j = np.array([1, 2, 3])
printa('j antes', j)

('j antes', array([1, 2, 3]))

In [147]:
k = j[:2]
k[0] = -100 # alteração de valor em K altera o valor de J
printa('j depois', j)

('j depois', array([-100,    2,    3]))

In [150]:
# para que isso não ocorra, precisa usar o copy()
l = j[:2].copy()
l[0] = 10
printa('j', j)

('j', array([-100,    2,    3]))

## 3. Funções aritméticas

In [153]:
base_um = np.ones((2, 2))
printa('base_um', base_um)

('base_um', array([[1., 1.],
        [1., 1.]]))

In [154]:
base_dois = np.eye(2)
printa('base_dois', base_dois)

('base_dois', array([[1., 0.],
        [0., 1.]]))

### 3.1 Soma

In [155]:
print('soma de dois arrays:\n', base_um + base_dois)
print('soma com float/int:\n', base_um + 2) # broadcasting

soma de dois arrays:
 [[2. 1.]
 [1. 2.]]
soma com float/int:
 [[3. 3.]
 [3. 3.]]


### 3.2 Subtração

In [156]:
print('substração de dois arrays:\n', base_um - base_dois)
print('substração com float/int:\n', base_um - 2) # broadcasting

substração de dois arrays:
 [[0. 1.]
 [1. 0.]]
substração com float/int:
 [[-1. -1.]
 [-1. -1.]]


### 3.3 Divisão

In [159]:
print('divisao de dois arrays:\n', base_um / base_dois) # se for uma divisao por zero, retorna infinito
print('divisao com float/int:\n', base_um / 2) # broadcasting

divisao de dois arrays:
 [[ 1. inf]
 [inf  1.]]
divisao com float/int:
 [[0.5 0.5]
 [0.5 0.5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


### 3.4 Broadcasting não funciona

In [161]:
#np.array([1, 2, 3]) + np.array([1, 2])

### 3.5 Combinação de operações

In [163]:
print('combinação de operações:\n', (base_um + base_dois) / (base_um - 2))

combinação de operações:
 [[-2. -1.]
 [-1. -2.]]


### 3.6 Multiplicação

#### 3.6.1 Elemento a elemento

In [166]:
print('multiplicação de dois arrays:\n', base_um * base_dois)
print('multiplicação com float/int:\n', base_dois * 2) # broadcasting

multiplicação de dois arrays:
 [[1. 0.]
 [0. 1.]]
multiplicação com float/int:
 [[2. 0.]
 [0. 2.]]


#### 3.6.2 Matricial

In [167]:
print('multiplicação matricial (np.dot):\n', np.dot(base_um, base_dois))
print('multiplicação matricial (@):\n',base_um @ base_dois)
print('multiplicação matricial (.dot):\n', base_um.dot(base_dois))

multiplicação matricial (np.dot):
 [[1. 1.]
 [1. 1.]]
multiplicação matricial (@):
 [[1. 1.]
 [1. 1.]]
multiplicação matricial (.dot):
 [[1. 1.]
 [1. 1.]]


## 4. Comparações

In [ ]:
m_um = np.array([[1, 2], [3, 4]])
printa('um:', m_um)

In [ ]:
m_dois = np.array([1.5, 3.5])
printa('dois:', m_dois)

### 4.1 Comparações elemento a elemento

In [ ]:
print('comparaçção de um array com um escalar (>):\n', m_um > 2)
print('comparaçção de um array com um escalar (>=):\n', m_um >= 2)
print('comparaçção de um array com um escalar (<):\n', m_um < 2)
print('comparaçção de um array com um escalar (<=):\n', m_um <= 2)
print('comparação entre arrays (==):\n', m_um == m_um)
print('comparação entre arrays (>):\n', m_um > m_um)
print('comparação entre arrays (>):\n', m_um > m_dois) # broadcasting
print('comparação entre arrays (<):\n', m_um < m_dois) # broadcasting

## 5. Indexação booleana

In [175]:
base = np.array([[1, 3, 7], [4, 11, 21], [42, 8, 9]])
print('x:\n', base)

x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


### 5.1 Retornar o numero de elementos maiores que a variavel K

In [180]:
k = 10
cond = base > k
print('condição:\n', cond)
print(f'elementos maiores que {k}:', base[cond])
print(f'numeros de elementos maiores que {k}:', len(base[cond]))

condição:
 [[False False False]
 [False  True  True]
 [ True False False]]
elementos maiores que 10: [11 21 42]
numeros de elementos maiores que 10: 3


### 5.2 Extração dos números pares

In [184]:
cond = base % 2 == 0
print('condição:\n', cond)
print('numeros pares:', base[cond])

condição:
 [[False False False]
 [ True False False]
 [ True  True False]]
numeros pares: [ 4 42  8]


### 5.3 Extração de números impares

In [185]:
cond = base % 2 == 1
print('condição:\n', cond)
print('numeros pares:', base[cond])

condição:
 [[ True  True  True]
 [False  True  True]
 [False False  True]]
numeros pares: [ 1  3  7 11 21  9]
