<a href="https://colab.research.google.com/github/icaloooou/bootcampIGTI/blob/main/%5BIGTI%5D_Bootcamp_Eng_de_Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 0. Imports

In [14]:
import numpy as np
import pandas as pd

## 1. Constants

In [ ]:
def printa(valor1, valor2):
  return valor1, valor2

In [ ]:
def shape(valor):
  return 'shape: ', valor.shape

# Numpy

> O numpy é uma das principais bibliotecas para
computação científica em Python.
> Disponibiliza um objeto de array multidimensional de alta
performance e diversas ferramentas para se trabalhar
com esses objetos.

## 1. Criação de Arrays

In [ ]:
help(np.array)  # o help serve para ver o que esse método aceita

### 1.1 Criação de array 1D

In [ ]:
lista = [1, 2, 3]
a = np.array(lista)
# x = np.array([1, 2, 3])

In [ ]:
printa('a', a)

('a', array([1, 2, 3]))

In [ ]:
shape(a)

('shape: ', (3,))

In [ ]:
type(a)

numpy.ndarray

### 1.2 Criação de array 2D: listas aninhadas

In [ ]:
lista = [[1, 2], [3, 4]]
b = np.array(lista)

In [ ]:
printa('b', b)

('b', array([[1, 2],
        [3, 4]]))

In [ ]:
shape(b)

('shape: ', (2, 2))

In [ ]:
type(b)

numpy.ndarray

### 1.3 Array contendo apenas 0's

In [ ]:
dim = (3, 2)
c = np.zeros(dim)

In [ ]:
printa('c', c)

('c', array([[0., 0.],
        [0., 0.],
        [0., 0.]]))

In [ ]:
shape(c)

('shape: ', (3, 2))

### 1.4 Array contendo apenas 1's

In [ ]:
size = (2, 2)
d = np.ones(size)

In [ ]:
printa('d', d)

('d', array([[1., 1.],
        [1., 1.]]))

In [ ]:
shape(d)

('shape: ', (2, 2))

### 1.5 Criação de valores dentro de um intervalo

In [ ]:
help(np.linspace)

In [ ]:
x_min, x_max = 5, 15
e = np.linspace(start=x_min, stop=x_max, num=6)

In [ ]:
printa('e', e)

('e', array([ 5.,  7.,  9., 11., 13., 15.]))

In [ ]:
shape(e)

('shape: ', (6,))

#### 1.6 Criação da matriz identidade

In [ ]:
n = 4 # recebe o mesmo numero de linhas e colunas
x = np.eye(n)

In [ ]:
print('x:\n', x)

x:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print('shape:', x.shape)

shape: (4, 4)


### 1.6 Criação de valores aleatórios

In [ ]:
f = np.random.random(size=(2, 3))

In [ ]:
printa('f', f)

('f', array([[0.77132064, 0.02075195, 0.63364823],
        [0.74880388, 0.49850701, 0.22479665]]))

In [ ]:
shape(f)

('shape: ', (2, 3))

## 2. Indexação de arrays

In [ ]:
g = np.linspace(10, 100, num=10)

In [ ]:
printa('g', g)

('g', array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]))

### 2.1 Arrays 1D

#### 2.1.1 Extração de elementos

In [ ]:
print('1:', g[0])
print('2:', g[1])
print('10:', g[9])
print('10:', g[-1])

1: 10.0
2: 20.0
10: 100.0
10: 100.0


#### 2.1.2 Slicing: extração de subarrays

In [ ]:
print('1 e 2:', g[0:2])
print('1 e 2:', g[:2])
print('9 e 10:', g[-2:])
print('9 e 10:', g[8:])

1 e 2: [10. 20.]
1 e 2: [10. 20.]
9 e 10: [ 90. 100.]
9 e 10: [ 90. 100.]


### 2.2 Reshape de arrays 2D (matrizes)

In [ ]:
h = g.reshape(2, 5) # reshape de g para 2 linhas e 5 colunas

In [ ]:
printa('h', h)

('h', array([[ 10.,  20.,  30.,  40.,  50.],
        [ 60.,  70.,  80.,  90., 100.]]))

In [ ]:
i = g.reshape(5, 2) # reshape de g para 5 linhas e 2 colunas

In [ ]:
printa('i', i)

('i', array([[ 10.,  20.],
        [ 30.,  40.],
        [ 50.,  60.],
        [ 70.,  80.],
        [ 90., 100.]]))

#### 2.2.1 Extração de elementos

In [ ]:
print('primeira linha, segunda coluna', h[0, 1])
print('segunda linha, penultima coluna', h[1, -2])
print('ultima linha, ultima coluna', h[-1, -1])
print('ultima linha, ultima coluna', h[1, 4])

primeira linha, segunda coluna 20.0
segunda linha, penultima coluna 90.0
ultima linha, ultima coluna 100.0
ultima linha, ultima coluna 100.0


#### 2.2.2 Slicing: estração de subarrays

In [ ]:
print('primeira linha inteira', h[0, :])
print('primeira linha, segunda a quarta coluna', h[0, 1:4])
print('ultima coluna inteira\n', h[:, [-1]]) # ao inserir o indice da coluna, ele retona na dimensao correta
print('ultima coluna inteira fora da dimensao', h[:, -1]) # fora da dimensao, veio como linha, sendo que é coluna

primeira linha inteira [10. 20. 30. 40. 50.]
primeira linha, segunda a quarta coluna [20. 30. 40.]
ultima coluna inteira
 [[ 50.]
 [100.]]
ultima coluna inteira fora da dimensao [ 50. 100.]


### 2.3 Compartilhamento de memória em subarrays

In [ ]:
j = np.array([1, 2, 3])
printa('j antes', j)

('j antes', array([1, 2, 3]))

In [ ]:
k = j[:2]
k[0] = -100 # alteração de valor em K altera o valor de J
printa('j depois', j)

('j depois', array([-100,    2,    3]))

In [ ]:
# para que isso não ocorra, precisa usar o copy()
l = j[:2].copy()
l[0] = 10
printa('j', j)

('j', array([-100,    2,    3]))

## 3. Funções aritméticas

In [ ]:
base_um = np.ones((2, 2))
printa('base_um', base_um)

('base_um', array([[1., 1.],
        [1., 1.]]))

In [ ]:
base_dois = np.eye(2)
printa('base_dois', base_dois)

('base_dois', array([[1., 0.],
        [0., 1.]]))

### 3.1 Soma

In [ ]:
print('soma de dois arrays:\n', base_um + base_dois)
print('soma com float/int:\n', base_um + 2) # broadcasting

soma de dois arrays:
 [[2. 1.]
 [1. 2.]]
soma com float/int:
 [[3. 3.]
 [3. 3.]]


### 3.2 Subtração

In [ ]:
print('substração de dois arrays:\n', base_um - base_dois)
print('substração com float/int:\n', base_um - 2) # broadcasting

substração de dois arrays:
 [[0. 1.]
 [1. 0.]]
substração com float/int:
 [[-1. -1.]
 [-1. -1.]]


### 3.3 Divisão

In [ ]:
print('divisao de dois arrays:\n', base_um / base_dois) # se for uma divisao por zero, retorna infinito
print('divisao com float/int:\n', base_um / 2) # broadcasting

divisao de dois arrays:
 [[ 1. inf]
 [inf  1.]]
divisao com float/int:
 [[0.5 0.5]
 [0.5 0.5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


### 3.4 Broadcasting não funciona

In [ ]:
#np.array([1, 2, 3]) + np.array([1, 2])

### 3.5 Combinação de operações

In [ ]:
print('combinação de operações:\n', (base_um + base_dois) / (base_um - 2))

combinação de operações:
 [[-2. -1.]
 [-1. -2.]]


### 3.6 Multiplicação

#### 3.6.1 Elemento a elemento

In [ ]:
print('multiplicação de dois arrays:\n', base_um * base_dois)
print('multiplicação com float/int:\n', base_dois * 2) # broadcasting

multiplicação de dois arrays:
 [[1. 0.]
 [0. 1.]]
multiplicação com float/int:
 [[2. 0.]
 [0. 2.]]


#### 3.6.2 Matricial

In [ ]:
print('multiplicação matricial (np.dot):\n', np.dot(base_um, base_dois))
print('multiplicação matricial (@):\n',base_um @ base_dois)
print('multiplicação matricial (.dot):\n', base_um.dot(base_dois))

multiplicação matricial (np.dot):
 [[1. 1.]
 [1. 1.]]
multiplicação matricial (@):
 [[1. 1.]
 [1. 1.]]
multiplicação matricial (.dot):
 [[1. 1.]
 [1. 1.]]


## 4. Comparações

In [ ]:
m_um = np.array([[1, 2], [3, 4]])
printa('um:', m_um)

In [ ]:
m_dois = np.array([1.5, 3.5])
printa('dois:', m_dois)

### 4.1 Comparações elemento a elemento

In [ ]:
print('comparaçção de um array com um escalar (>):\n', m_um > 2)
print('comparaçção de um array com um escalar (>=):\n', m_um >= 2)
print('comparaçção de um array com um escalar (<):\n', m_um < 2)
print('comparaçção de um array com um escalar (<=):\n', m_um <= 2)
print('comparação entre arrays (==):\n', m_um == m_um)
print('comparação entre arrays (>):\n', m_um > m_um)
print('comparação entre arrays (>):\n', m_um > m_dois) # broadcasting
print('comparação entre arrays (<):\n', m_um < m_dois) # broadcasting

## 5. Indexação booleana

In [ ]:
base = np.array([[1, 3, 7], [4, 11, 21], [42, 8, 9]])
print('x:\n', base)

x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


### 5.1 Retornar o numero de elementos maiores que a variavel K

In [ ]:
k = 10
cond = base > k
print('condição:\n', cond)
print(f'elementos maiores que {k}:', base[cond])
print(f'numeros de elementos maiores que {k}:', len(base[cond]))

condição:
 [[False False False]
 [False  True  True]
 [ True False False]]
elementos maiores que 10: [11 21 42]
numeros de elementos maiores que 10: 3


### 5.2 Extração dos números pares

In [ ]:
cond = base % 2 == 0
print('condição:\n', cond)
print('numeros pares:', base[cond])

condição:
 [[False False False]
 [ True False False]
 [ True  True False]]
numeros pares: [ 4 42  8]


### 5.3 Extração de números impares

In [ ]:
cond = base % 2 == 1
print('condição:\n', cond)
print('numeros pares:', base[cond])

condição:
 [[ True  True  True]
 [False  True  True]
 [False False  True]]
numeros pares: [ 1  3  7 11 21  9]


## 6. Dicas úteis

In [3]:
base = np.array([[1, 3, 7], [4, 11, 21], [42, 8, 9]])
print('x:\n', base)

x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


### 6.1 reshape: transformar a matriz em um vetor coluna e um vetor linha

In [ ]:
print('transformação de uma matriz em um vetor coluna:\n', base.reshape(9,1))
print('transformação de uma matriz em um vetor linha:\n', base.reshape(1,9))

### 6.2 Transposição de matriz > o que era linha vira coluna e o que era coluna vira linha

In [6]:
print('base transposta:\n', base.T)

base transposta:
 [[ 1  4 42]
 [ 3 11  8]
 [ 7 21  9]]


### 6.3 np.sum e np.mean

#### 6.3.1 soma em um dado eixo, axis = {0: linha, 1: coluna}

In [9]:
print('soma de todos elementos da base:\n', np.sum(base))
print('soma da base ao longo das linhas:', np.sum(base, axis=0))
print('soma da base ao longo das colunas:', np.sum(base, axis=1))

soma de todos elementos da base:
 106
soma da base ao longo das linhas: [47 22 37]
soma da base ao longo das colunas: [11 36 59]


#### 6.3.2 média em um dado eixo, axis = {0: linha, 1: coluna}

In [10]:
print('médi de todos elementos da base:\n', np.mean(base))
print('média da base ao longo das linhas:', np.mean(base, axis=0))
print('média da base ao longo das colunas:', np.mean(base, axis=1))

médi de todos elementos da base:
 11.777777777777779
média da base ao longo das linhas: [15.66666667  7.33333333 12.33333333]
média da base ao longo das colunas: [ 3.66666667 12.         19.66666667]


### 6.4 np.where > identificação dos índices onde uma dada condição é atendida. Uso conjunto com indexação booleana

In [12]:
cond = base % 2 == 0
print('condição:\n', cond)
y, z = np.where(cond)
print('índice y (linhas):', y)
print('índice z (colunas):', z)

condição:
 [[False False False]
 [ True False False]
 [ True  True False]]
índice y (linhas): [1 2 2]
índice z (colunas): [0 0 1]


### 6.5 indexação booleana e slicing

#### 6.5.1 selecionar as linhas que possuem algum numero par

In [13]:
cond = base % 2 == 0
print('condição:\n', cond)

# se houver alguma condiçao True na linha, a soma será > 0
row = np.where(np.sum(cond, axis=1))[0]
print('índice das linhas que possuem números pares:', row)
print('linhas que possuem números pares: \n', base[row, :])

condição:
 [[False False False]
 [ True False False]
 [ True  True False]]
índice das linhas que possuem números pares: [1 2]
linhas que possuem números pares: 
 [[ 4 11 21]
 [42  8  9]]


# Pandas

> Pandas é um pacote em Python desenvolvido para disponibilizar
estruturas de dados rápidas e flexíveis para se trabalhar com dados
“relacionais” ou “rotulados”. Ele é adequado para diversos tipos de
dados.

## 1. Leitura de dados

### 1.1 csv

In [15]:
df = pd.read_csv('https://pycourse.s3.amazonaws.com/temperature.csv')
df

date  temperatura classification
0  2020-01-01         29.1         quente
1  2020-02-01         31.2   muito quente
2  2020-03-01         28.5         quente
3  2020-04-01         28.0         quente
4  2020-05-01         24.0    confortavel
5  2020-06-01         20.0           frio

### 1.2 excel

In [18]:
# aqui vai ler o arquivo todo (todas as sheets)
excel_file = pd.ExcelFile('https://pycourse.s3.amazonaws.com/temperature.xlsx')

In [22]:
# leitura da primeira aba (sheet1)
df2 = pd.read_excel(excel_file, sheet_name='Sheet1')
df2

date  temperatura classification
0 2020-01-01         29.1         quente
1 2020-02-01         31.2   muito quente
2 2020-03-01         28.5         quente
3 2020-04-01         28.0         quente
4 2020-05-01         24.0    confortavel
5 2020-06-01         20.0           frio

In [26]:
# leitura da segunda aba (sheet2)
df3 = pd.read_excel(excel_file, sheet_name='Sheet2')
df3

date temperatura classification
0 2020-01-01        29,1         quente
1 2020-02-01        31,2   muito quente
2 2020-03-01        28,5         quente
3 2020-04-01        28,0         quente
4 2020-05-01        24,0    confortavel
5 2020-06-01        20,0           frio

## 2. Visualização

### 2.1 Visualizando as n primeiras linhas

In [27]:
n = 3
df.head(n)

date  temperatura classification
0  2020-01-01         29.1         quente
1  2020-02-01         31.2   muito quente
2  2020-03-01         28.5         quente

### 2.2 Visualizando as últimas n linhas

In [28]:
n = 3
df.tail(n)

date  temperatura classification
3  2020-04-01         28.0         quente
4  2020-05-01         24.0    confortavel
5  2020-06-01         20.0           frio

### 2.3 Tipos

In [30]:
# visualização dos tipos de cada coluna
df.dtypes

date               object
temperatura       float64
classification     object
dtype: object

### 2.4 Estatisticas básicas

In [31]:
df.describe()

temperatura
count     6.000000
mean     26.800000
std       4.075782
min      20.000000
25%      25.000000
50%      28.250000
75%      28.950000
max      31.200000

### 2.5 Dataframe info

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   date            6 non-null      object 
 1   temperatura     6 non-null      float64
 2   classification  6 non-null      object 
dtypes: float64(1), object(2)
memory usage: 272.0+ bytes


### 2.6 Nome das colunas

In [33]:
df.columns

Index(['date', 'temperatura', 'classification'], dtype='object')

In [34]:
# para renomear é facil
df.columns = ['col1', 'col2', 'col3']

In [35]:
df

col1  col2          col3
0  2020-01-01  29.1        quente
1  2020-02-01  31.2  muito quente
2  2020-03-01  28.5        quente
3  2020-04-01  28.0        quente
4  2020-05-01  24.0   confortavel
5  2020-06-01  20.0          frio

# Trabalho prático e Desafio final > módulo 2

In [39]:
# CÓDIGO 1
Z = np.zeros((4, ))
print('Z:', Z)

Z: [0. 0. 0. 0.]


In [40]:
# CÓDIGO 2
Z = np.zeros((4,))
Z[1] = 1.
print('Z:', Z)

Z: [0. 1. 0. 0.]


In [41]:
# CÓDIGO 3
Z = np.zeros((4,))
Z[1:] = 1.
print('Z:', Z)

Z: [0. 1. 1. 1.]


In [49]:
# CÓDIGO 4
Z = np.ones((4,))
Z[-1] = 0.
print('Z:', Z)
# saida: Z: [1. 1. 1. 0.]

Z: [1. 1. 1. 0.]


In [51]:
# CÓDIGO 5 
X = 2*np.ones((2, 2))
print('X:\n', X)
# saida X: [[2. 2.]
#           [2. 2.]]

X:
 [[2. 2.]
 [2. 2.]]


In [52]:
# CÓDIGO 6
X = np.array([[1, 2], [3, 4]])
Y = X[0, :]
Y[1] = 10
print('X:\n', X)

X:
 [[ 1 10]
 [ 3  4]]


In [53]:
# CÓDIGO 7
X = np.array([[1, 3], [11, 10]])
print(np.mean(X[X > np.pi]))

10.5


In [54]:
# CÓDIGO 8
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog',
                   'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7 ,3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no',
                     'no', 'no', 'yes', 'no', 'no']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [78]:
# CÓDIGO 9
df = pd.DataFrame(data=data, index=labels)
#df
#df.shape
#df['animal'].value_counts()
#df.describe()
#df['visits']


animal  age  visits priority
a    cat  2.5       1      yes
g  snake  4.5       1       no
h    cat  NaN       1      yes
j    dog  3.0       1       no
c  snake  0.5       2       no
e    dog  5.0       2       no
i    dog  7.0       2       no
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no

In [79]:
# CÓDIGO 10
y_true = np.array([1., 2., 1.])
y_pred = np.array([1.1, 1.98, 1.05])
np.sqrt(((y_true-y_pred)**2).mean())

0.06557438524302006